### ISSUE TITLE
Eq. 2.12 - principal rotation around x

### ISSUE THREAD

**Issue by bjornrho** [tussedrotten/vslam-handbook#3]
The matrix in equation 2.12 has a '1' instead of a '0' in the first row/third column.

**Comment by tussedrotten** [comment]
Whoops, how has that stayed there for so long? 😮 
Thanks! Will fix immediately

**Comment by tussedrotten** [comment]
Fixed in [version 0.0.2](https://github.com/tussedrotten/vslam-handbook/releases/tag/v0.0.2)
